### ISSUE TITLE
超时异常处理出错

### ISSUE THREAD

**Issue by imp0wd3r** [knownsec/Pocsuite#91] opened 2016-07-03 06:13 UTC
site-packages/pocsuite/lib/controller/controller.py", line 95, in pocThreads
![screenshot from 2016-07-03 14 12 08](https://cloud.githubusercontent.com/assets/17606044/16544046/4d52bb3a-4128-11e6-837f-902a5a3ad036.png)

**Comment by join-us** [comment] 2016-07-04 03:35
Please update your pocsuite code, and the issue is fixed in [previous commit](https://github.com/knownsec/Pocsuite/blob/dev/pocsuite/lib/controller/controller.py#L95). Redirects to the [pr](https://github.com/knownsec/Pocsuite/pull/90).

**Closed** 2016-07-04 12:58 UTC
